### ISSUE TITLE
VXPayPaymentTab is not passing flowOptions in mobile

### ISSUE THREAD

**Issue by maddockman** [VISIT-X/vxpay-js#19]
> Please describe the issue in as many details as possible.

cc @t1gor

## Versions:
- the latest vxpay-js version is affected

## Problem
When trying to pass flowOptions to the new window (tab) in mobile, the options are not passed to the VXPay App at all.

## Details....
The flowOptions should be passed to the new tab. In the VXPayPaymentTab, the prop _loaded is probably never set to true and that's why the flowOptions are always passed to the invisible iframe.

## Possible solutions
The flowOptions should be passed to the tab via postMessages only then, when the tab has received the message "ContentLoaded". That means, the VXPay App is ready to receiver postMessages and react to the appropriately.

**Comment by maddockman** [comment]
@t1gor It's strange, because postMessage was always working for cross-domain windows and frames. Even got it working in a quick fix for tabs and mobile in the demo page. I was able to pass postMessage from the .x domain to the .net domain.

But you are right, the load event is impossible to get. We are for this reason passing the postMessage ContentLoaded message, which need to be used.

If I have some time, I'll try to send my solution proposal as a quick fix.

Otherwise, the oAuth way would be the best and it would solve our another problem with the integrate Android Browser, which opens new tabs in chrome

**Comment by t1gor** [comment]
@maddockman, don’t you mind just changing the posted above jsbin sample for the sake of time? I mean I couldn’t get the postMessage for loaded content there eaither.

**Comment by maddockman** [comment]
I've updated the jsbin sample with an ugly code snippet, which works. This is just an example, not the final solution.

But with it, I was able to send postMessage from .x domain to the real .net domain.

**Comment by maddockman** [comment]
Hi Igor,

my working solution. Please, just look over it, if it's suitable for you :)


https://gist.github.com/maddockman/ae18fc3f4c5e246d517af6fc4c000bb0

**Comment by t1gor** [comment]
#20 created to address the issue. Will be merged and released as soon as Travis builds pass.
