### ISSUE TITLE
Changing vxpay language

### ISSUE THREAD

**Issue by florindumitrescu95** [VISIT-X/vxpay-js#25]
## Problem
> What are you trying to achieve and what's not right?

Unable to directly set vxpay language, only when you initialize 

## Details....
> Any stack traces, failed commands or environment details you could provide would be helpful.

To change the language on the vxpay, i'm required to modify the parameter of the VXPayConfig object to the language wanted and then reinitialize the VXPay object. While doing so, first 2 language changes doesn't modify the language in the modals and from the 3rd time it does change but it doesn't keep the whole configuration (promotional picture of the model doesn't appear).

## Possible solutions
> If you know the solution already, please describe it here.

VXPay should have a method that allows the language to be changed from this object without reinitializing another one on every language change using the a new configuration. 
Ex: 
```javascript
const vxpayConfig = new VXPayConfig(window);
vxpayConfig.language = 'DE';
const vxpay = new VXPay(vxpayConfig); // default language
```
on external change it could be called like so:
```javascript
vxpay.changeLanguage(newLanguage); 
```

**Comment by t1gor** [comment]
@maddockman does the vxpay iframe support changing the language by post-message? Or should it just be re-loaded? I would really prefer the first option, to be honest.

**Comment by maddockman** [comment]
Hi,

no, it's not possible at the moment, just reload with the language parameter.

**Comment by florindumitrescu95** [comment]
@t1gor 

TypeError: this.vxpay.changeLanguage is not a function
 -this is what i get, even though there is a function created within the Vxpay class.

On a closer look over the [[Prototype]] property of the vxpay object, i observed that the changeLanguage method does not appear and i believe thats why it doesnt recognize the method. After a more analyze over the vxpay package, every function bound to vxpay object is defined within with a key and the function but has several functions for each method like getPrototype, setProtoype, inherits, possibleConstructorReturn, and the changeLanguage (from all the ones i searched within the project) is the only one without those helper functions

**Comment by t1gor** [comment]
@florindumitrescu95 are you sure you've installed beta? The version you need to install is `2.6.0-beta.0`. To install it via npm, please use:

```bash
npm install vxpay-js@2.6.0-beta.0
```

To check that you've got the right package, you can then use grep to check the source:

```bash
cat node_modules/vxpay-js/dist/vxpay.js | grep changeLanguage
```

The output should look something like this:
```
    key: "changeLanguage",
    value: function changeLanguage(lng) {
```

Please drop me a line in Skype (UID: igor_timoshenkov) if that doesn't work for you.
