### ISSUE TITLE
Change language triggers the login modal

### ISSUE THREAD

**Issue by t1gor** [VISIT-X/vxpay-js#31]
## Versions:
- `vxpay-js`: `2.6.0`

## Problem
changing language triggers the login modal

## Details....
From @florindumitrescu95:
> and it happens only on the 2nd language i want to change, like, if i start the page with DE as first language, it will trigger it only when i'm changing the language to EN
> it doesnt happen to DE
> same if i start with EN as first language, changing to DE will trigger the modal, but going back to EN wont

**Comment by florindumitrescu95** [comment]
@t1gor https://codesandbox.io/s/xjx8pr1nmp i was able to partially reproduce it, it happens only once though , it would require too much code to reproduce exactly but i believe its what you need. Check in withAuth, initializeSession

**Comment by t1gor** [comment]
@florindumitrescu95 we seem to have found the issue. The new version `2.6.1` is [currently building](https://travis-ci.org/VISIT-X/vxpay-js/builds/481398188), package will be released when done. Please test a new version and let us know if that works for you.

**Comment by t1gor** [comment]
@florindumitrescu95 can we close this issue? Please let me know.

**Comment by t1gor** [comment]
Your codesandbox works fine with v2.6.1 

[![Edit vxpay-js-change-language-v2.6.1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8n2q5qrxq8)

**Comment by florindumitrescu95** [comment]
@t1gor problem solved, you can close the issue
