### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by florindumitrescu95** [VISIT-X/vxpay-js#33]
> Please describe the issue in as many details as possible.

Anything with a higher z-index of 1 would stay over the modal. 

cc @t1gor

## Solution
> If you know the solution already, please describe it here.

Adding an z-index on the iframe thats being inserted in the page would solve the problem. The problem occurs that even though that a div inside has a z-index of 9999, the whole DOM inside the iframe its at z-index of default, meaning that every z-index of higher than 1 will stay over the iframes content.

**Comment by florindumitrescu95** [comment]
![screenshot from 2019-02-05 14-02-46](https://user-images.githubusercontent.com/25899739/52272499-a80b9f80-294f-11e9-84e8-24e8ea9dab4a.png)

**Comment by t1gor** [comment]
@florindumitrescu95 thanks for reporting, we'll take a look at this.

**Comment by stha** [comment]
@t1gor Could you please fix that issue. Z-Index should be setable over an eligible config option with a proper default value. At the moment it breaks the VXPage.

**Comment by t1gor** [comment]
Guys, sorry for the delays - the issue should be fixed in [v2.6.2](https://github.com/VISIT-X/vxpay-js/releases/tag/2.6.2)

**Comment by t1gor** [comment]
@florindumitrescu95 please confirm if the issue can be closed

**Comment by florindumitrescu95** [comment]
@t1gor works
