### ISSUE TITLE
Extend VXPay Api with pfmsub

### ISSUE THREAD

**Issue by maddockman** [VISIT-X/vxpay-js#38]
Hi @t1gor,

we need to extend the VXPayConfig with a new parameters:

pfmsub = <string>

The behaviour should be exact the same like the pfm parameter:
  - new VXPayConfig parameter
  - the pfmsub parameter will be then part of the paytour url: 

e.g.:
...pfm=1502&pfmsub=h12361&..

https://github.com/VISIT-X/vxpay-js/blob/63a8c74e1b60dcc4d7bdb1dfb3d8583bf486ab99/src/VXPay/VXPayConfig.js#L28

Thank you,
PH

**Comment by t1gor** [comment]
@maddockman version [2.6.3](https://www.npmjs.com/package/vxpay-js/v/2.6.3) released with the changes you made. Please confirm.

**Comment by maddockman** [comment]
Looks good to me, @t1gor!

Thx 👍
