### ISSUE TITLE
VXPayConfig - ref parameter has a wrong value

### ISSUE THREAD

**Issue by maddockman** [VISIT-X/vxpay-js#39]
> Please describe the issue in as many details as possible.

cc @t1gor

## Versions:
- current

## Problem
I guest, there's a wrong value for the "ref" VXPayConfig parameter. It should not be wmId but the HTTP_REFERER value

https://github.com/VISIT-X/vxpay-js/blob/9783ae2ba19ea3293c74f74d5287b0e4d618b384/src/VXPay/VXPayConfig.js#L125

## Possible solutions
Just add the possibility to set the REFERRER via setter. It should be part of the urls object 
(this._urls.ref = ref)

VXPayConfig.ref = 'https://www.google.com/?q=visit-x'

Thanks :)

**Comment by t1gor** [comment]
@maddockman version [2.6.3](https://www.npmjs.com/package/vxpay-js/v/2.6.3) released with the changes you made. Please confirm.

**Comment by maddockman** [comment]
LGTM, @t1gor !

Thx 👍
