### ISSUE TITLE
Typo in the props and methods - abg vs. agb

### ISSUE THREAD

**Issue by maddockman** [VISIT-X/vxpay-js#52]
There's a typo in the Config Prop "agbUrl". Everywhere there's a wrong name:

abg* instead of agb*

cc @t1gor

- Refactoring needed to set the correct properties:

=> agbUrl

**Comment by t1gor** [comment]
@maddockman new version released with the fix: 2.10.1. Please confirm if the issue is solved and we can close it.

**Comment by maddockman** [comment]
Looks good @t1gor, thx!
