### ISSUE TITLE
openVXAboPaytour flow - missing feature

### ISSUE THREAD

**Issue by maddockman** [VISIT-X/vxpay-js#58]
This is just a reminder for the missing feature, which has been implemented in the old library and will be needed some time, when switching to vxpay-js

openVXAboPaytour()

**Comment by t1gor** [comment]
Is this the one addressed in #64 ?

**Comment by t1gor** [comment]
@maddockman can we close this one?

**Comment by maddockman** [comment]
@t1gor Hi Igor, this functionality was then not used in the product and I don't know the current plans. So we can either let it open und implement when needed, or close now and open a new issue, as soon as it's needed?

**Comment by maddockman** [comment]
I'll close :)
